-- V1__Create_initial_schema.sql
-- Creates the initial database schema for the Personal Finance Manager

CREATE TABLE IF NOT EXISTS CATEGORY (
    ID_CATEGORY INTEGER PRIMARY KEY AUTOINCREMENT,
    DESCRIPTION varchar(255) NOT NULL UNIQUE,
    TYPE varchar(20) NOT NULL CHECK(TYPE IN ('INCOMES', 'EXPENSES'))
);

CREATE TABLE IF NOT EXISTS TRANSACTIONS (
    ID_TRANSACTION INTEGER PRIMARY KEY AUTOINCREMENT,
    AMOUNT DECIMAL(10, 2) NOT NULL,
    TRANSACTION_DATE DATE NOT NULL,
    ID_CATEGORY INTEGER,
    COMMENT varchar(255) NULL,
    FOREIGN KEY (ID_CATEGORY) REFERENCES CATEGORY(ID_CATEGORY)
);

