-- V2__Insert_initial_data.sql
-- Inserts initial categories and sample transactions

-- Insert initial categories with TYPE
INSERT INTO CATEGORY (DESCRIPTION, TYPE) VALUES ('Salary', 'INCOMES');
INSERT INTO CATEGORY (DESCRIPTION, TYPE) VALUES ('Food & Groceries', 'EXPENSES');
INSERT INTO CATEGORY (DESCRIPTION, TYPE) VALUES ('Transportation', 'EXPENSES');
INSERT INTO CATEGORY (DESCRIPTION, TYPE) VALUES ('Entertainment', 'EXPENSES');
INSERT INTO CATEGORY (DESCRIPTION, TYPE) VALUES ('Utilities', 'EXPENSES');
INSERT INTO CATEGORY (DESCRIPTION, TYPE) VALUES ('Healthcare', 'EXPENSES');
INSERT INTO CATEGORY (DESCRIPTION, TYPE) VALUES ('Investment', 'EXPENSES');
INSERT INTO CATEGORY (DESCRIPTION, TYPE) VALUES ('Other Income', 'INCOMES');
INSERT INTO CATEGORY (DESCRIPTION, TYPE) VALUES ('Other Expenses', 'EXPENSES');

-- Insert sample transactions
INSERT INTO TRANSACTIONS (AMOUNT, TRANSACTION_DATE, ID_CATEGORY, COMMENT)
VALUES (5000.00, '2026-02-01', 1, 'Monthly salary');

INSERT INTO TRANSACTIONS (AMOUNT, TRANSACTION_DATE, ID_CATEGORY, COMMENT)
VALUES (250.50, '2026-02-05', 2, 'Supermarket shopping');

INSERT INTO TRANSACTIONS (AMOUNT, TRANSACTION_DATE, ID_CATEGORY, COMMENT)
VALUES (50.00, '2026-02-07', 3, 'Gas station');

INSERT INTO TRANSACTIONS (AMOUNT, TRANSACTION_DATE, ID_CATEGORY, COMMENT)
VALUES (100.00, '2026-02-10', 4, 'Cinema tickets');

INSERT INTO TRANSACTIONS (AMOUNT, TRANSACTION_DATE, ID_CATEGORY, COMMENT)
VALUES (150.00, '2026-02-12', 5, 'Electricity bill');

INSERT INTO TRANSACTIONS (AMOUNT, TRANSACTION_DATE, ID_CATEGORY, COMMENT)
VALUES (1000.00, '2026-02-15', 8, 'Stock dividend');

