server:
  port: 8080

spring:
  application:
    name: ai-finance-manager

  datasource:
    url: jdbc:sqlite:finance_manager.db
    driver-class-name: org.sqlite.JDBC

  jpa:
    database-platform: org.hibernate.community.dialect.SQLiteDialect
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true


logging:
  level:
    org.flywaydb: INFO

datawrapper:
  access-token: ${DATAWRAPPER_ACCESS_TOKEN}

mcp:
  client:
    enabled: true #${MCP_CLIENT_ENABLED:false}
    command: ${MCP_CLIENT_COMMAND:/Users/ystaro/.local/bin/datawrapper-mcp}

